### PR TITLE
Make partition lock count configurable from Makefile

### PR DESCRIPTION
**Pull request by timrc-git**
#62 has been languishing, so here's a Makefile settable scale-factor or static-value.

I manually tested it with different options (I'm not going to try to make unit tests that change the Makefile config).

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by areese** [comment]
@timrc-git can you resign the CLA, it's confused and thinks you haven't signed it.

**Comment by timrc-git** [comment]
Signed. Not sure how long it takes to update...

**Comment by areese** [comment]
@timrc-git thanks.

**Pull request merged**
