### PR TITLE
Fix error: ‘template<class> class std::auto_ptr’ is deprecated

### PR DESCRIPTION
**Pull request by guoxiao**
use `unique_ptr` instead

### CODE REVIEW

**Comment by areese** [comment]
@guoxiao, it seems like the build failed:
"CppUnitTestRunnerLocal.cc:158:5: error: ‘unique_ptr’ does not name a type
CppUnitTestRunnerLocal.cc:160:5: error: ‘unique_ptr’ does not name a type
CppUnitTestRunnerLocal.cc: In constructor ‘ComboOutputter::ComboOutputter(CppUnit::TestResultCollector*, const string&)’:"

Does unique_ptr only exist on a newer c++ standard?

**Comment by steve-carney** [comment]
Unique_ptr is from newish c++11.  Not all of the internal stack has upgraded to this newer version.

**Comment by guoxiao** [comment]
Since the default build options include `-Werror` so the build will fail with newer compiler.

I think I should add some check and use `auto_ptr` and `unique_ptr` for old and new compiler separately.

**Comment by areese** [comment]
@steve-carney I'm more worried about failing on new compilers than doing internal fixups.

Is there an ifdef we can use to pick if it should be auto_ptr or unique_ptr?

**Comment by areese** [comment]
duh.  Nevermind that:
"
+#include <memory>    // unique_ptr
 +#if __cplusplus <= 199711L
 +  #define unique_ptr auto_ptr
 +#endif
"

That works for me.

Thanks @guoxiao, I think this is good.

**Pull request merged**
